name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build

      - name: Publish to registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
